/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class TelaA extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlta
     */
    public TelaA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCid10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtConclusao = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ALTA");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Motivo da Alta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 16);
        getContentPane().add(txtMotivo);
        txtMotivo.setBounds(10, 30, 660, 110);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("CID10");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 70, 50);
        getContentPane().add(txtCid10);
        txtCid10.setBounds(10, 190, 90, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Conclusão do Atendimento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 250, 180, 20);
        getContentPane().add(txtConclusao);
        txtConclusao.setBounds(10, 280, 340, 100);

        btnGravar.setBackground(new java.awt.Color(0, 0, 255));
        btnGravar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGravar.setForeground(new java.awt.Color(255, 255, 255));
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(10, 420, 130, 30);

        btnVoltar.setBackground(new java.awt.Color(0, 0, 255));
        btnVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(160, 420, 130, 30);

        setSize(new java.awt.Dimension(846, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
      boolean r;
        TelaAlta t;
        TelaAltaDao tela;

        t = new TelaAlta();
        t.setMotivo(txtMotivo.getText());
        t.setCId10(txtCid10.getText());
        t.setConclusao(txtCid10.getText());
       
       
        tela = new TelaAltaDao();
        r = tela.conectar();
        if (r == true) {
            r = tela.salvar(t);
            if (r == true) {
                JOptionPane.showMessageDialog(null, "Informações Salvas com sucesso");
                
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não conectou");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.disable();
        TelaCadastroPaciente tela;
        tela = new TelaCadastroPaciente();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCid10;
    private javax.swing.JTextField txtConclusao;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
