/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author casa
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmissão
     */
    public TelaAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQueixa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtQueixa = new javax.swing.JTextField();
        lblDataPrimeiroSintoma = new javax.swing.JLabel();
        txtDataPrimeiroSintoma = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblCovidConfirmado = new javax.swing.JLabel();
        lblPlanoTerapeutico = new javax.swing.JLabel();
        txtPlanoTerapeutico = new javax.swing.JTextField();
        lblDiagnostico = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        lblCid10 = new javax.swing.JLabel();
        txtCid10 = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        lblNomePaciente = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        cmbCovidConfirmado = new javax.swing.JComboBox<>();
        lblDataAtendimento = new javax.swing.JLabel();
        txtDataAtendimento = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        scrollbar2 = new java.awt.Scrollbar();

        setTitle("ADMISSÃO");
        getContentPane().setLayout(null);

        lblQueixa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblQueixa.setText("Queixa Principal/Histôria");
        getContentPane().add(lblQueixa);
        lblQueixa.setBounds(10, 140, 210, 15);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 240, 960, 0);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 60, 960, 10);

        txtQueixa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtQueixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueixaActionPerformed(evt);
            }
        });
        getContentPane().add(txtQueixa);
        txtQueixa.setBounds(10, 160, 930, 110);

        lblDataPrimeiroSintoma.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDataPrimeiroSintoma.setText("Data Primeiros Sintomas (dd/mm/aaaa)");
        getContentPane().add(lblDataPrimeiroSintoma);
        lblDataPrimeiroSintoma.setBounds(10, 70, 220, 10);

        txtDataPrimeiroSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPrimeiroSintomaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataPrimeiroSintoma);
        txtDataPrimeiroSintoma.setBounds(10, 90, 130, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 130, 950, 30);

        lblCovidConfirmado.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCovidConfirmado.setText("COVID confirmado ?");
        getContentPane().add(lblCovidConfirmado);
        lblCovidConfirmado.setBounds(480, 70, 120, 20);

        lblPlanoTerapeutico.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblPlanoTerapeutico.setText("Plano Terapêutico");
        getContentPane().add(lblPlanoTerapeutico);
        lblPlanoTerapeutico.setBounds(10, 490, 120, 30);

        txtPlanoTerapeutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlanoTerapeuticoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlanoTerapeutico);
        txtPlanoTerapeutico.setBounds(10, 520, 930, 110);

        lblDiagnostico.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDiagnostico.setText("Diagnóstico");
        getContentPane().add(lblDiagnostico);
        lblDiagnostico.setBounds(10, 290, 150, 15);
        getContentPane().add(txtDiagnostico);
        txtDiagnostico.setBounds(10, 310, 930, 110);

        lblCid10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCid10.setText("CID10");
        getContentPane().add(lblCid10);
        lblCid10.setBounds(10, 430, 80, 15);
        getContentPane().add(txtCid10);
        txtCid10.setBounds(10, 450, 190, 30);

        btnGravar.setBackground(new java.awt.Color(0, 0, 255));
        btnGravar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGravar.setForeground(new java.awt.Color(255, 255, 255));
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(10, 660, 120, 30);

        btnConsultar.setBackground(new java.awt.Color(0, 0, 255));
        btnConsultar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(150, 660, 130, 30);

        btnAvancar.setBackground(new java.awt.Color(0, 0, 255));
        btnAvancar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAvancar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar);
        btnAvancar.setBounds(300, 660, 120, 30);

        lblNomePaciente.setText("Nome Paciente");
        getContentPane().add(lblNomePaciente);
        lblNomePaciente.setBounds(10, 0, 90, 20);
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(10, 20, 490, 30);

        cmbCovidConfirmado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informe", "Sim", "Não" }));
        getContentPane().add(cmbCovidConfirmado);
        cmbCovidConfirmado.setBounds(450, 90, 170, 30);

        lblDataAtendimento.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDataAtendimento.setText("Data do Atendimento (dd/mm/aaaa)");
        getContentPane().add(lblDataAtendimento);
        lblDataAtendimento.setBounds(570, 0, 230, 15);
        getContentPane().add(txtDataAtendimento);
        txtDataAtendimento.setBounds(570, 20, 130, 30);

        btnLimpar.setBackground(new java.awt.Color(0, 0, 255));
        btnLimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(440, 660, 130, 30);
        getContentPane().add(scrollbar2);
        scrollbar2.setBounds(940, -20, 16, 720);

        setSize(new java.awt.Dimension(969, 762));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQueixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueixaActionPerformed

    private void txtDataPrimeiroSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPrimeiroSintomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPrimeiroSintomaActionPerformed

    private void txtPlanoTerapeuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlanoTerapeuticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlanoTerapeuticoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        boolean r;
        TelaAdmissao t;
        TelaAdmissaoDao tela;

        t = new TelaAdmissao();
        t.setNomePaciente(txtNomePaciente.getText());
        t.setDataPrimeiroSintoma(txtDataPrimeiroSintoma.getText());
        t.setCovidConfirmado(cmbCovidConfirmado.getSelectedItem().toString());
        t.setQueixa(txtQueixa.getText());
        t.setDiagnostico(txtDiagnostico.getText());
        t.setCid10(txtCid10.getText());
        t.setPlanoTerapeutico(txtPlanoTerapeutico.getText());
        t.setDataAtendimento(txtDataAtendimento.getText());

        tela = new TelaAdmissaoDao();
        r = tela.conectar();
        if (r == true) {
            r = tela.salvar(t);
            if (r == true) {
                JOptionPane.showMessageDialog(null, "Informações Salvas com sucesso");
                Limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não conectou");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            Connection con;
            PreparedStatement st;
            ResultSet rs;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            st = con.prepareStatement("SELECT * FROM  admissao WHERE DataAtendimento = ?");

            st.setString(1, txtDataAtendimento.getText());
            rs = st.executeQuery();

            if (rs.next()) {
                txtNomePaciente.setText(rs.getString("NomePaciente"));
                txtDataPrimeiroSintoma.setText(rs.getString("DataPrimeiroSintoma"));
                cmbCovidConfirmado.setSelectedItem(rs.getString("CovidConfirmado"));
                txtQueixa.setText(rs.getString("Queixa"));
                txtDiagnostico.setText(rs.getString("Diagnostico"));
                txtCid10.setText(rs.getString("Cid10"));
                txtPlanoTerapeutico.setText(rs.getString("PlanoTerapeutico"));
                txtDataAtendimento.setText(rs.getString("DataAtendimento"));

            } else {
                JOptionPane.showMessageDialog(null, "Informações Não Encontradas");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no no acesso ao Banco de Dados entre em contato com o adm" + ex.getMessage());

        }


    }//GEN-LAST:event_btnConsultarActionPerformed
    private void Limpar() {
        txtNomePaciente.setText("");
        txtDataPrimeiroSintoma.setText("");
        cmbCovidConfirmado.setSelectedItem("Informe");
        txtQueixa.setText("");
        txtDiagnostico.setText("");
        txtCid10.setText("");
        txtPlanoTerapeutico.setText("");
        txtDataAtendimento.setText("");
        txtDataAtendimento.requestFocus();
    }


    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        this.disable();
        TelaEvolucao tela;
        tela = new TelaEvolucao();
        tela.setVisible(true);
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbCovidConfirmado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCid10;
    private javax.swing.JLabel lblCovidConfirmado;
    private javax.swing.JLabel lblDataAtendimento;
    private javax.swing.JLabel lblDataPrimeiroSintoma;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblPlanoTerapeutico;
    private javax.swing.JLabel lblQueixa;
    private java.awt.Scrollbar scrollbar2;
    private javax.swing.JTextField txtCid10;
    private javax.swing.JTextField txtDataAtendimento;
    private javax.swing.JTextField txtDataPrimeiroSintoma;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtPlanoTerapeutico;
    private javax.swing.JTextField txtQueixa;
    // End of variables declaration//GEN-END:variables
}
