
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class TelaExames extends javax.swing.JFrame {

    /**
     * Creates new form TelaExames
     */
    public TelaExames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        lblExames = new javax.swing.JLabel();
        txtExames = new javax.swing.JTextField();
        lblCid10 = new javax.swing.JLabel();
        txtCid10 = new javax.swing.JTextField();
        lblConclusao = new javax.swing.JLabel();
        txtConclusao = new javax.swing.JTextField();
        lblDataAtendimento = new javax.swing.JLabel();
        txtDataAtendimento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setTitle("EXAMES");
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        lblExames.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblExames.setText("Exames");
        getContentPane().add(lblExames);
        lblExames.setBounds(10, 0, 90, 20);

        txtExames.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtExames.setInheritsPopupMenu(true);
        txtExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExamesActionPerformed(evt);
            }
        });
        getContentPane().add(txtExames);
        txtExames.setBounds(10, 20, 370, 110);

        lblCid10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCid10.setText("CID10");
        getContentPane().add(lblCid10);
        lblCid10.setBounds(10, 160, 60, 20);
        getContentPane().add(txtCid10);
        txtCid10.setBounds(10, 180, 120, 30);

        lblConclusao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblConclusao.setText("Conclusão");
        getContentPane().add(lblConclusao);
        lblConclusao.setBounds(10, 250, 120, 20);
        getContentPane().add(txtConclusao);
        txtConclusao.setBounds(10, 270, 370, 110);

        lblDataAtendimento.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDataAtendimento.setText("Data do Atendimento (dd/mm/aaaa)");
        getContentPane().add(lblDataAtendimento);
        lblDataAtendimento.setBounds(450, 0, 240, 30);
        getContentPane().add(txtDataAtendimento);
        txtDataAtendimento.setBounds(450, 30, 150, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 430, 120, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Avançar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 430, 120, 30);

        setSize(new java.awt.Dimension(730, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     boolean r;
        TelaExa telaEx;
        TelaExamesDao telaExam;

        telaEx = new TelaExa();
        telaEx.setExames(txtExames.getText());
        telaEx.setDataAtendimento(txtDataAtendimento.getText());
        telaEx.setCid10(txtCid10.getText());
        telaEx.setConclusao(txtConclusao.getText());
       
        telaExam = new TelaExamesDao();
        r = telaExam.conectar();
        if (r == true) {
            r = telaExam.salvar(telaEx);
            if (r == true) {
                JOptionPane.showMessageDialog(null, "Informações Salvas com sucesso");
                
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não conectou");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.disable();
        TelaMed tela;
        tela = new TelaMed();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JLabel lblCid10;
    private javax.swing.JLabel lblConclusao;
    private javax.swing.JLabel lblDataAtendimento;
    private javax.swing.JLabel lblExames;
    private javax.swing.JTextField txtCid10;
    private javax.swing.JTextField txtConclusao;
    private javax.swing.JTextField txtDataAtendimento;
    private javax.swing.JTextField txtExames;
    // End of variables declaration//GEN-END:variables
}
