
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class TelaEvolucao extends javax.swing.JFrame {

    /**
     * Creates new form TelaEvolucao
     */
    public TelaEvolucao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEvolucao = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        lblNomePaciente = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtDataAtendimento = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();

        setTitle("EVOLUÇÃO");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Evolução Médica");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 130, 19);
        getContentPane().add(txtEvolucao);
        txtEvolucao.setBounds(10, 110, 910, 230);

        btnGravar.setBackground(new java.awt.Color(0, 0, 255));
        btnGravar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGravar.setForeground(new java.awt.Color(255, 255, 255));
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(10, 370, 120, 30);

        lblNomePaciente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblNomePaciente.setText("Nome Paciente");
        getContentPane().add(lblNomePaciente);
        lblNomePaciente.setBounds(10, 0, 100, 15);
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(10, 20, 490, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 940, 2);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Data Atendimento (dd/mm/aaaa)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 0, 180, 15);
        getContentPane().add(txtDataAtendimento);
        txtDataAtendimento.setBounds(570, 20, 120, 30);

        btnAvancar.setBackground(new java.awt.Color(0, 0, 255));
        btnAvancar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAvancar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar);
        btnAvancar.setBounds(150, 370, 120, 30);

        setSize(new java.awt.Dimension(949, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        boolean r;
        TelaEvo telaEv;
        TelaEvolucaoDao telaE;

        telaEv = new TelaEvo();
        telaEv.setNomePaciente(txtNomePaciente.getText());
        telaEv.setDataAtendimento(txtDataAtendimento.getText());
        telaEv.setEvolucao(txtEvolucao.getText());
       
        telaE = new TelaEvolucaoDao();
        r = telaE.conectar();
        if (r == true) {
            r = telaE.salvar(telaEv);
            if (r == true) {
                JOptionPane.showMessageDialog(null, "Informações Salvas com sucesso");
                
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar salvar os dados");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não conectou");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        this.disable();
        TelaExames tela;
        tela = new TelaExames();
        tela.setVisible(true);
    }//GEN-LAST:event_btnAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEvolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEvolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEvolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEvolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEvolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JTextField txtDataAtendimento;
    private javax.swing.JTextField txtEvolucao;
    private javax.swing.JTextField txtNomePaciente;
    // End of variables declaration//GEN-END:variables
}
